name: aclc_clinic
description: "student view."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4 
  printing: ^5.11.1
  http: ^1.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  device_preview: ^1.3.1
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  google_fonts: ^8.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # Merged here

flutter:
  uses-material-design: true
  assets:
    - assets/ACLC.svg
    - assets/Logo.png # Added this so Flutter recognizes your icon file

# This section must be at the root level (no indentation)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ACLC.png" 
  adaptive_icon_background: "#FFFFFF"    
  adaptive_icon_foreground: "assets/ACLC.png"